version: "3.7"

services:
  --service_name--_server:
    container_name: "--service_name---service"
    build:
      context: .
    command: npm run start:dev
    volumes:
      - .:/opt/node_app:delegated
      - ./package.json:/opt/node_app/package.json
      - ./package-lock.json:/opt/node_app/package-lock.json
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://user:pass@--service_name--_psql:5432/postgres
    ports:
      - "6004:6001"
    depends_on:
      - --service_name--_psql

  --service_name--_psql:
    container_name: "--service_name---psql"
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    ports:
      - 5400:5432

volumes:
  --service_name--:
